import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";

import { ReactQueryProviderClient } from "@/providers/react-query-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReactQueryProviderClient>
          <NuqsAdapter>{children}</NuqsAdapter>
        </ReactQueryProviderClient>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
